#!/bin/bash
git clone https://github.com/CTFd/CTFd.git
cd CTFd

sed -i "s/status, message = chal_class.attempt(challenge, request)/status, message = chal_class.attempt(challenge, request, user)/g" CTFd/api/v1/challenges.py

sed -i "s/def attempt(cls, challenge, request):/def attempt(cls, challenge, request, user):/g" CTFd/plugins/challenges/__init__.py

sed -i.bak "s|flags = Flags.query.filter_by(challenge_id=challenge.id).all()|flags = Flags.query.filter_by(challenge_id=challenge.id).all()\
\n        user_id=int(user.id)\
\n        import hashlib\
\n        string_1=b\"String1\" \
\n        string_2=b\"String2\" \
\n        string_3=b\"String3\" \
\n        flag_hash=hashlib.sha256(string_1+int(user_id).to_bytes(4, byteorder='big')+string_2+int(challenge.id).to_bytes(4, byteorder='big')+string_3).hexdigest()\
\n        if submission==\"flag{\"+flag_hash+\"}\":\
\n            return True, \"Correct\"|g" CTFd/plugins/challenges/__init__.py

# docker-compose up


